class Strings {
  static const String APP_NAME = "Yemek Tarifleri";

  static const List<String> YEMEK_ADLARI = [
    "Kabak Mücver",
    "Alinazik",
    "Bolonez Soslu Makarna",
    "Soğan Halkası",
    "Dalyan Köfte",
    "Et Sote",
    "Limonlu Yoğurtlu Kek",
    "İzmir Köfte",
    "Sebze Çorbası",
    "Kakaolu Islak Kek",
    "İslim Kebabı",
    "Kısır",
    "Fırında Köfte Patates",
    "Kıbrıs Tatlısı",
    "Franbuazlı Cheesecake"
  ];

  static const List<String> HAZIRLANMA_SURESI = [
    "15 dakika",
    "15 dakika",
    "15 dakika",
    "45 dakika",
    "30 dakika",
    "20 dakika",
    "15 dakika",
    "15 dakika",
    "15 dakika",
    "20 dakika",
    "30 dakika",
    "10 dakika",
    "30 dakika",
    "20 dakika",
    "20 dakika"
  ];

  static const List<String> YEMEK_TARIFI = [
    "\t3 adet kabak\n\n"
        "\t2 adet yumurta(çırpılmış)\n\n"
        "\t1 adet havuç \n\n"
        "\t3 kahve fincanı un \n\n"
        "\t1 demet taze soğan  \n\n"
        "\t1 demet dereotu \n\n"
        "\t1 tatlı kaşığı tuz \n\n"
        "\t1 çay kaşığı karabiber\n\n"
        "\tBol suda yıkadığınız kabakları rendenin iri kısmıyla rendeleyin. \n\n"
        "\tMücveri sulandırmaması için; rendelenmiş kabakların suyunu sıkarak çıkartın.\n\n"
        "\tGeniş bir kapta rendelenen kabakları, havucu, 2 adet çırpılmış yumurtayı, 1 demet taze soğanı, 1 demet dereotunu, 1 tatlı kaşığı tuzu, karabiberi ve 3 kahve fincanı unu birleştirin.\n\n"
        "\tTüm malzemeler birbiriyle harmanlanıp, macun kıvamını alana kadar spatula yardımıyla karıştırın.Her bir mücver 1 tepeleme yemek kaşığı olacak şekilde ayarlayın.\n\n"
        "\tKızgın yağda altın sarısı rengini alana kadar kızartın. \n\n"
        "\tMücverlerin fazla yağını havlu kağıda süzdürdükten sonra servis tabağına alın ve çırpılmış yoğurt ile servis edin. \n\n\n",
    "\tMalzemeler:\n\n"
        "\t1 diş sarımsak\n\n"
        "\t250 gram kuşbaşı et (küçük doğranmış)\n\n"
        "\t50 gram tereyağı\n\n"
        "\t1 yemek kaşığı biber salçası\n\n"
        "\t1 çay kaşığı toz kırmızı biber\n\n"
        "\t1 çay kaşığı tuz\n\n"
        "\tPatlıcanlı karışım için:\n\n"
        "\t3 adet közlenmiş patlıcan\n\n"
        "\t1 çay kaşığı tuz\n\n"
        "\t1 kase sarımsaklı yoğurt\n\n"
        "\tTarif:\n\n"
        "\tTereyağını derin bir tavanın içine alın. Sarımsağı ilave ederek hafifçe soteleyin\n\n"
        "\tArdından minik doğranmış kuşbaşı etleri ekleyerek karıştırın, kapağını kapatıp 6-7 dakika kısık ateşte suyunu salıp pişene kadar bırakın.\n\n"
        "\tPiştikten sonra salça, toz kırmızı biber ve tuz ekleyerek tatlandırın ve ocaktan alın.\n\n"
        "\tKözlenmiş patlıcanları kesme tahtasının üzerinde keskin bir bıçak yardımıyla dövün. Dövme aşamasında üzerine hafifçe tuz atın.\n\n"
        "\tİyice ezildiklerinde sarımsaklı yoğurt ile bir kasenin içinde birleştirin ve güzelce karıştırın.\n\n"
        "\tServis tabağının içerisine yoğurtlu patlıcanlı karışımı alın. Ortasını çukurlaştırın.\n\n"
        "\tHazırladığınız etleri de üzerine yerleştirin. Sosunu ilave ederek servis edin.    \n\n",
    "\t   Malzemeler:\n\n"
        "\t   1 paket  Makarna \n\n"
        "\t   8 su bardağı su \n\n"
        "\t   1 yemek kaşığı zeytinyağı \n\n"
        "\t   1 çay kaşığı tuz\n\n"
        "\t   Bolonez sos için:\n\n"
        "\t   2 yemek kaşığı zeytinyağı\n\n"
        "\t   400 gram kıyma\n\n"
        "\t   1 adet orta boy kuru soğan\n\n"
        "\t   1 diş sarımsak\n\n"
        "\t   1 adet orta boy havuç \n\n"
        "\t   3 adet orta boy domates\n\n"
        "\t   1 tatlı kaşığı domates salçası \n\n"
        "\t   1/2 su bardağı su (makarna haşlama ya da et suyu) \n\n"
        "\t   1/2 çay kaşığı tuz  \n\n"
        "\t   1/2 çay kaşığı taze çekilmiş tane karabiber \n\n"
        "\t   1 tatlı kaşığı kekik \n\n"
        "\t Tarif:\n\n"
        "\t Makarnayı haşlamak için; suyu derin bir tencereye aktarın. Zeytinyağı ve tuz ilavesi ile kaynatın.\n\n"
        "\t Kaynayan suya penne makarnaları atıp, damak tadınıza göre 10- 12 dakika kadar haşlayın. \n\n"
        "\t Bolonez sosu hazırlamak için; kabuğunu soyduğunuz kuru soğanı küçük küpler halinde kesin, domatesleri küp küp doğrayın. \n\n"
        "\t Aynı şekilde kabuğunu soyduğunuz havucu rendenin iri kısmıyla rendeleyin. Sarımsağı küçük küpler halinde doğrayın. \n\n"
        "\t Zeytinyağını sos tenceresinde kızdırın. Doğranmış kuru soğanları katıp, hafif bir renk alana kadar kavurun. Aralarda karıştırarak sırasıyla; rendelenmiş sarımsak ve havucu ekleyin. \n\n"
        "\t Kıymayı kattıktan sonra renk alana kadar kavurma işlemini sürdürün. Doğranmış domates, domates salçası, tuz, taze çekilmiş tane karabiber ve kekik ilave edin.\n\n"
        "\t Son olarak su eklediğiniz sosu, orta ateşte 5- 6 dakika kadar kaynatın. \n\n"
        "\t Haşlanmış makarnanın suyunu süzün. Bekletmeden hazırladığınız sıcak bolonez sos ile makarnayı harmanladıktan sonra rendelenmiş parmesan peyniri ilavesi ile sıcak olarak servis edin.\n\n",
    "\t   Malzemeler:\n\n"
        "\t   2 adet büyük boy kuru soğan\n\n"
        "\t   1 adet yumurta\n\n"
        "\t   1/2 su bardağı maden suyu\n\n"
        "\t   1/2 su bardağı süt\n\n"
        "\t   3 yemek kaşığı un\n\n"
        "\t   3 yemek kaşığı mısır nişastası\n\n"
        "\t   1 çay kaşığı kabartma tozu ya da karbonat\n\n"
        "\t   1/2 çay kaşığı tuz\n\n"
        "\t   1/4 çay kaşığı karabiber\n\n"
        "\t   1/4 çay kaşığı kırmızı toz biber\n\n"
        "\t   Kızartmak için:\n\n"
        "\t   1 su bardağı bayat ekmek içi ya da galeta unu\n\n"
        "\t   1,5 su bardağı ayçiçek yağı\n\n"
        "\t Uç kısımları aldığınız kuru soğanların kabuklarını dikkatli bir şekilde soyun.\n\n"
        "\t Kabuğunu soyduğunuz soğanları yarım santimetre kalınlığında halka halka dilimleyin. Her bir soğan dilimini kendi halkalarına ayırın.\n\n"
        "\t Çıtır kaplama harcı için; yumurta, süt, maden suyu, elenmiş un, mısır nişastası, kabartma tozu, tuz, karabiber ve kırmızı toz biberi derin bir kapta bir çırpıcı yardımıyla karıştırın.\n\n"
        "\t Hazırladığınız kaplama harcını, pürüzsüz bir kıvamda olması için tel süzgeçten geçirip ayrı bir yere alın.\n\n"
        "\t Ayçiçek yağını geniş tabanlı bir tavada kızdırın. Galeta unu ya da çekilmiş bayat ekmek içini düz bir tabağa alın.\n\n"
        "\t İnce ince halkalarına ayrılmış her bir soğan halkasını öncelikle kaplama harcına batırıp fazlasını aldıktan sonra galeta ununa bulayın.\n\n"
        "\t Kızdırılmış yağa bıraktığınız soğan halkalarını, aralarda bir kevgir yardımıyla karıştırarak altın sarısı bir renk alana kadar kızartın.\n\n"
        "\t Fazla yağını bırakmaları için kısa bir süre kağıt havlu üzerinde beklettiğiniz çıtır soğan halkalarını, ev yapımı soslar eşliğinde sevdiklerinizle paylaşın.\n\n",
    "\t Malzemeler:\n\n"
        "\t 1 kilogramdana kıyma\n\n"
        "\t 2 adet soğan(rendelenmiş)\n\n"
        "\t 1 su bardağı galeta unu\n\n"
        "\t 2 adet yumurta\n\n"
        "\t 1/2 su bardağı sıvı yağ\n\n"
        "\t 2 çay kaşığı tuz\n\n"
        "\t 1 çay kaşığı karabiber\n\n"
        "\t 2 çay kaşığı pul biber\n\n"
        "\t 1 adet havuç(haşlanmış)\n\n"
        "\t 1 su bardağı bezelye(halanmış)\n\n"
        "\t 5 adet yumurta(haşlanmış, köftenin içine dolgu için)\n\n"
        "\t 1 yemek kaşığı domates salçası\n\n"
        "\t 1/2 su bardağı su\n\n"
        "\t Tarif:\n\n"
        "\t Bir yoğurma kabına kıyma, soğan, yumurta, galeta unu, sıvı yağ, tuz, karabiber ve pul biberi ekleyip karıştırın.\n\n"
        "\t İyice yoğurulan kıymayı pişirme kağıdının üzerine alın.\n\n"
        "\t Kıymayı rulo haline gelebilecek şekle getirin ve tam ortasına bir çukur açın.\n\n"
        "\t Açtığınız çukurun içerisine önce bezelyelerin yarısını ve haşlanmış uzun şeritler halinde kesilmiş havuçları yerleştirin.\n\n"
        "\t Haşlanmış, soğumuş yumurtaları da dik bir şekilde ortaya dizdikten sonra geri kalan bezelyeler ile boşlukları doldurun.\n\n"
        "\t Kıymayı, harcı kapatacak şekilde dikkatlice rulo haline getirin ve pişirme kağıdını kapatarak yuvarlayın ve kenarlarından kapatın.\n\n"
        "\t Üzerine bir kat daha pişirme kağıdı sardıktan sonra 200 derece fırında 45 dakika pişirin.\n\n"
        "\t 45 dakika sonunda köfteyi fırından çıkarın ve salçalı suyu köftenin üzerine, her yerine gelecek şekilde dökün ve yayın.\n\n"
        "\t Soslanan köfteyi 15 dakika daha fırına verin.\n\n"
        "\t Fırından çıktıktan sonra dilimleyerek servis edin.\n\n",
    "\t Malzemeler:\n\n"
        "\t 600 gram sotelik dana eti\n\n"
        "\t 4 yemek kaşığı zeytinyağı\n\n"
        "\t 1 adet orta boy kuru soğan(yemeklik doğranmış)\n\n"
        "\t 2 adet orta boy domates(kabukları soyulmuş, doğranmış)\n\n"
        "\t 3 adet orta boy yeşil biber(doğranmış)\n\n"
        "\t 1 tatlı kaşığı domates salçası\n\n"
        "\t 1/2 tatlı kaşığı biber salçası\n\n"
        "\t 1 su bardağı sıcak su\n\n"
        "\t 1 çay kaşığı tuz\n\n"
        "\t 1/2 çay kaşığı taze çekilmiş tane karabiber\n\n"
        "\t 1 tatlı kaşığı kekik\n\n"
        "\t Tarif:\n\n"
        "\t Döküm bir tavada 4 yemek kaşığı zeytinyağını kızdırın. 1 adet yemeklik ince doğradığınız soğanları tavaya ekleyin.\n\n"
        "\t Renk alan soğanların üzerine 3 adet doğranmış yeşil biber ekleyin ve sotelemeye devam edin.\n\n"
        "\tSotelik doğradığınız 600 gram dana etini ilave edin.\n\n"
        "\t Suyunu salmaması, lezzet ve vitamin değerini hapsetmesi için; yüksek ateşte, yaklaşık 2-3 dakika hiç karıştırmadan mühürleyin.\n\n"
        "\t Dış kısmı renk alan etleri aralarda karıştırarak yüksek ateşte sotelemeye devam edin.\n\n"
        "\t 3 adet soyulmuş ,doğranmış domatesi ekleyerek karıştırın. Ardından 1 çay kaşığı tuz, karabiber, 1 tatlı kaşığı kekiği de ekleyin.\n\n"
        "\t Birer yemek kaşığı biber ve domates salçasını 1 su bardağı sıcak su ile sulandırdıktan sonra azar azar tavaya ekleyin.\n\n"
        "\t Kısık ateşte etler yumuşayana kadar pişirin.\n\n"
        "\t Etleri yumuşayan soteyi, lezzetli suyuyla birlikte servis tabaklarına alın ve sıcak sıcak servis edin.\n\n",
    "\t Malzemeler:\n\n"
        "\t 3 adet yumurta\n\n"
        "\t 1 su bardağı yoğurt (sulu bir kıvamda)\n\n"
        "\t 3/4 su bardağı sıvı yağ\n\n"
        "\t 1 su bardağı toz şeker\n\n"
        "\t 1 adet limon kabuğu rendesi\n\n"
        "\t 1 adet limonun suyu\n\n"
        "\t 2 yemek kaşığı haşhaş\n\n"
        "\t 2 paket vanilya\n\n"
        "\t 1 paket kabartma tozu\n\n"
        "\t 3,5 - 4 su bardağı un\n\n"
        "\t Tarif:\n\n"
        "\t Yumurtaları derin bir kabın içerisine kırın. Üzerine toz şeker ilave edip güzelce çırpmaya başlayın.\n\n"
        "\t Ardından sıvı yağ ve yoğurdu ekleyerek çırpma işlemine devam edin.\n\n"
        "\t Limon kabuğu rendesi ve vanilyayı bir kabın içerisinde güzelce ovun ve harca ilave edin.\n\n"
        "\t Limon suyunu, sıvı yağ ve haşhaşı da ekleyerek çırpmaya devam edin.\n\n"
        "\t Hazırladığınız harca unu azar azar bir şekilde eleyerek ilave edin.\n\n"
        "\t Mikser yardımıyla çırpın ya da spatula yardımıyla alttan üste doğru güzelce karıştırın.\n\n"
        "\t Ardından yağlanmış unlanmış bir kek kalıbına kek harcını aktarın. 180 derecede önceden ısıtılmış fırında 30-40 dakika arasında pişirin.\n\n"
        "\t Pişince fırından alın ve oda sıcaklığında dinlenmeye bırakın. Tamamen soğuduğunda dilimleyerek servis edin. Afiyetler olsun!\n\n",
    "\t Malzemeler:\n\n"
        "\t 500 gram dana kıyma\n\n"
        "\t 1 adet rendelenmiş soğan\n\n"
        "\t 3 yemek kaşığı galeta unu\n\n"
        "\t 1 çay kaşığı tuz\n\n"
        "\t 1 çay kaşığı kimyon\n\n"
        "\t 1 adet yumurta\n\n"
        "\t 1 diş rendelenmiş sarımsak\n\n"
        "\t 4 adet patates(elma dilimi doğranmış)\n\n"
        "\t 2 adet domates\n\n"
        "\t 2 yemek kaşığı domates salçası\n\n"
        "\t 1/4 su bardağı sıvı yağ\n\n"
        "\t 1 su bardağı su\n\n"
        "\t 1 çay kaşığı tuz\n\n"
        "\t 1 çay kaşığı karabiber\n\n"
        "\t Tarif:\n\n"
        "\t Kıymayı karıştırma kabına alın.\n\n"
        "\t Üzerine rendelenmiş soğan, sarımsak, galeta unu, yumurta ve baharatları ekleyip yoğurun. Yoğurduğunuz köfteye şekil verin ve yağda kızartın.\n\n"
        "\t Elma dilimi doğranmış patatesleri yağda kızartın. Tepsiye kızarttığınız patates ve köfteleri dizin. Üzerine domates ve biberleri ekleyin.\n\n"
        "\t Su, salça, yağ, kekik ve tuzu bir kapta karıştırın. Karışımı köftelerin üzerine dökün ve 175 derecelik fırında 30 dakika pişirin. Ardından çıkarıp servis edebilirsiniz. Afiyet olsun.\n\n",
    "\t Malzemeler:\n\n"
        "\t 2 adet havuç\n\n"
        "\t 2 adet kabak\n\n"
        "\t 2 adetbiber\n\n"
        "\t 1/4 adet karnabahar(dilediğiniz sebzeyi ekleyebilir veya çıkartabilirsiniz)\n\n"
        "\t 3 yemek kaşığı un\n\n"
        "\t 1-2 yemek kaşığı tereyağı veya sıvı yağ\n\n"
        "\t 5 su bardağı tavuk suyu(dilerseniz sıcak suyla da yapabilirsiniz)\n\n"
        "\t 1,5 tatlı kaşığı tuz\n\n"
        "\t 1 çay kaşığı nane\n\n"
        "\t 1 çay kaşığı toz acı biber\n\n"
        "\t Tarif:\n\n"
        "\t Öncelikle havuç ve kabağı rendeleyip, biberleri ince ince doğruyoruz.\n\n"
        "\t Hazır olan sebzeleri bir kenara alıp yağımızı tencereye koyup ısıtıyoruz. Isınan yağa unu ekleyip hafifçe kavuruyoruz.\n\n"
        "\t Ardından sebzelerimizi de tencereye ilave ediyoruz.\n\n"
        "\t Bir iki dakika sebzelerimizi karıştırıp daha sonra suyumuzu ekliyoruz. Yaklaşık on beş dakika orta ateşte kaynayan çorbamızı ocaktan almadan önce tuzunu ve baharatlarını ilave ediyoruz.\n\n"
        "\t İsterseniz blenderdan geçirip ya da direkt bu şekilde servis edebilirsiniz. Afiyet olsun...\n\n",
    "\t Malzemeler:\n\n"
        "\t 3 adet yumurta\n\n"
        "\t 1 su bardağı toz şeker\n\n"
        "\t 1 su bardağı süt\n\n"
        "\t 1 su bardağı ayçiçek yağı\n\n"
        "\t 1 paket vanilya\n\n"
        "\t 2 yemek kaşığı kakao\n\n"
        "\t 1 paket kabartma tozu\n\n"
        "\t 1 su bardağı un+2 yemek kaşığı un\n\n"
        "\t Kek kalıbını yağlamak için:\n\n"
        "\t 1 yemek kaşığı sıvı yağ\n\n"
        "\t Sosu İçin:\n\n"
        "\t 1 su bardağı süt(daha ıslak isterseniz süt miktarını arttırabilirsiniz)\n\n"
        "\t 4 yemek kaşığı kakao\n\n"
        "\t 1 su bardağı toz şeker\n\n"
        "\t 1 çay bardağı sıvı yağ\n\n"
        "\t 1/2 çay kaşığı tuz\n\n"
        "\t Tarif:\n\n"
        "\t Derin bir kasede yumurta ve şekeri aktarın.\n\n"
        "\t Şeker eriyip, karışım krema kıvamına gelene kadar çırpın.\n\n"
        "\t Ardından içerisine sütü, sıvı yağı ilave edin.\n\n"
        "\t Vanilini de ekleyin. Koyup tekrar karıştırın.\n\n"
        "\t Topak kalmaması için kakao, kabartma tozu ve unu süzgeçten geçirin.\n\n"
        "\t Karışıma ekleyin.\n\n"
        "\t Son bir kez daha güzelce çırpın.\n\n"
        "\t Yağlanmış, ısıya dayanıklı bir kabın içerisine karışımı dökdükten sonra önceden ısıtılmış 180 derece fırında yaklaşık 30 dakika pişirin.\n\n"
        "\t Keki ıslatmak için bir sos tenceresinde süt, toz şekeri aktarın.\n\n"
        "\tSıvı yağı da ilave edin.\n\n"
        "\tKakao ve bir tutam tuzu karıştırıp bir taşım kaynatın.\n\n"
        "\t Kaynayınca ocaktan alın.\n\n"
        "\tFırından çıkan kekin üzerine ocakta hazırladığımız sosu dökün ve çekmesini bekleyin.\n\n"
        "\t Sosunu sünger gibi çeken iç kısmı yumuşacık ıslak keki dilimledikten sonr üzerine file badem serpiştirerek servis edin, sevdiklerinizle afiyetle tüketin.\n\n",
    "\t Malzemeler:\n\n"
        "\t 4 adet orta boy patlıcan\n\n"
        "\t 3 yemek kaşığı zeytinyağı\n\n"
        "\t 2 adet orta boy domates\n\n"
        "\t 2 adet orta boy yeşil biber\n\n"
        "\t Köftesi için:\n\n"
        "\t 500 gram orta yağlı kıyma\n\n"
        "\t 1 adet orta boy kuru soğan(rendelenmiş)\n\n"
        "\t 4 yemek kaşığı galeta unu\n\n"
        "\t 2 diş sarımsak(ezilmiş)\n\n"
        "\t 1 adet yumurta\n\n"
        "\t 1 çay kaşığı tuz\n\n"
        "\t 1 çay kaşığı pul biber\n\n"
        "\t 1 çay kaşığı kimyon\n\n"
        "\t 1 çay kaşığı karabiber\n\n"
        "\t Sosu için:\n\n"
        "\t 2 yemek kaşığı zeytinyağı\n\n"
        "\t 2 adet domates(rendelenmiş)\n\n"
        "\t 1 diş sarımsak(ezilmiş)\n\n"
        "\t 1/2 su bardağı sıcak su\n\n"
        "\t 1/2 çay kaşığı tuz\n\n"
        "\t 1 çay kaşığı karabiber\n\n"
        "\t Tarif:\n\n"
        "\t Kabuklarını alacalı şekilde soyduğunuz patlıcanları keskin bir bıçak yardımıyla uzun ince şeritler halinde dilimleyin. Acısının çıkması için tuzlu suda bekletin.\n\n"
        "\t Orta yağlı dana kıymayı karıştırma kabına alın. Rendelenmiş kuru soğan, yumurta ve galeta unu, sarımsak, tuz, karabiber, pul biber ve kimyon katın.\n\n"
        "\t Köfte harcını özleşene kadar yaklaşık 10-15 dakika yoğurun.\n\n"
        "\t Köfte harcını altı cevizden biraz daha büyük parçalar ayırın. Avuç içinizde yuvarladığınız köfteleri,  tavada arkalı önlü ters çevirerek pişirin.\n\n"
        "\t Tuzlu suda dinlenen patlıcanların suyunu süzüp bol suda durulayın. Üzerlerini bir kağıt havlu yardımıyla kurulayın. Yağı kızdırdığınız tavada arkalı önlü ters çevirerek kızartın. Fazla yağını kağıt havlu yardımıyla alın.\n\n"
        "\t Sap kısımlarını aldığınız yeşil biberleri dört eşit parçaya bölün. Cherry domatesleri ikiye bölün.\n\n"
        "\t İki adet kızarmış patlıcan şeridini artı şeklini alacak şekilde servis tabağına yerleştirin. Orta kısmına bir adet kızarmış köfte koyup kapatın. Üzerine bir parça yeşil biber ve cherry domates yerleştirip kürdanla tutturun.\n\n"
        "\t Tüm köfteleri aynı şekilde patlıcan şeritlerine sardıktan sonra fırın tepsisine yerleştirin.\n\n"
        "\t Sosu için; zeytinyağını küçük bir sos tenceresinde kızdırın. Rendelenmiş domates ve  sarımsağı pişirin. Tuz ve karabiberini de ekledikten sonra 4-5 dakika kadar kaynatıp ocaktan alın.\n\n"
        "\t Hazırladığınız sosu patlıcanları aldığınız fırın tepsisine aktarın. İslim kebaplarını önceden ısıtılmış 180 derece fırında 30 dakika kadar pişirdikten sonra sıcak olarak servis edin.\n\n",
    "\t Malzemeler:\n\n"
        "\t 2 su bardağı ince bulgur\n\n"
        "\t 1,5 su bardağı sıcak su\n\n"
        "\t 2 yemek kaşığı domates salçası\n\n"
        "\t 1 çay bardağı zeytinyağı\n\n"
        "\t 1 tatlı kaşığı tuz\n\n"
        "\t 1 tatlı kaşığı pul biber\n\n"
        "\t 2 adet limon suyu\n\n"
        "\t 1/2 çay bardağı nar ekşisi\n\n"
        "\t 6 dal taze soğan\n\n"
        "\t 1/2 demet maydanoz\n\n"
        "\t 1/2 demet taze nane\n\n"
        "\t Tarif:\n\n"
        "\t 2 su bardağı ince bulguru geniş bir kaseye alın. Üzerine 1,5 su bardağı sıcak suyu ekleyin.\n\n"
        "\t Streç film ile üzerini kapatıp bugurların şişmesini bekleyin.Bulgurlar şiştikten sonra tane tane olması için güzelce karıştırın.\n\n"
        "\t Üzerine 2 yemek kaşığı domates salçası ve 1 çay bardağı zeytinyağını ekleyin.\n\n"
        "\t 1 tatlı kaşığı tuz, 1 tatlı kaşığı pul biber, 2 limonun suyu ve yarım çay bardağı nar ekşisini de ekleyin.\n\n"
        "\t Son olarak doğradığınız 6 dal taze soğanı, yarım demet taze nane ve maydanozu da ekleyip karıştırdıktan sonra kısır servise hazır.\n\n"
        "\t Yanında marullarla ya da dilediğiniz malzemelerle servis edebilirsiniz. Afiyet olsun!\n\n",
    "\t Malzemeler:\n\n"
        "\t 3 adet orta boy patates\n\n"
        "\t 1 adet orta boy kuru soğan\n\n"
        "\t 1 adet orta boy domates\n\n"
        "\t 2 adet orta boy kırmızı biber\n\n"
        "\t Köfte harcı için:\n\n"
        "\t 500 gram orta yağlı dana kıyma\n\n"
        "\t 1 adet rendelenmiş kuru soğan\n\n"
        "\t 1 adet yumurta\n\n"
        "\t 2 yemek kaşığı galeta unu (arzuya göre bayat ekmek içi)\n\n"
        "\t 10 dal maydanoz\n\n"
        "\t 1 çay kaşığı tuz\n\n"
        "\t 1 çay kaşığı karabiber\n\n"
        "\t 1 çay kaşığı kimyon\n\n"
        "\t 1 çay kaşığı yenibahar\n\n"
        "\t Sosu için:\n\n"
        "\t 2 yemek kaşığı ayçiçek yağı (arzuya göre zeytinyağı)\n\n"
        "\t 1 yemek kaşığı domates salçası\n\n"
        "\t 1,5 su bardağı sıcak su\n\n"
        "\t 1/2 çay kaşığı tuz\n\n"
        "\t Tarif:\n\n"
        "\t Köfteleri hazırlamak için; 500 gram orta yağlı kıymayı derin bir karıştırma kabına alın. 1 adet rendelenmiş kuru soğan, 2 yemek kaşığı galeta unu, 1 adet yumurta, 1 avuç kıyılmış maydanoz yaprakları   ilave edin.\n\n"
        "\t Birer çay kaşığı karabiber, tuz ve kimyon ekleyin.\n\n"
        "\t Köftenin harcını güzelce yoğurmaya başlayın.\n\n"
        "\t Hazırladığınız köfte harcından parçalar koparıp elinizle yuvarlak şekil verdiğiniz köfteler hazırlayın.\n\n"
        "\t Sosu için; 2 yemek kaşığı ayçiçek yağını küçük bir sos tenceresinde kızdırın.\n\n"
        "\t 1 yemek kaşığı domates salçasını ekleyip kısa süre kavurun. 2 adet rendelenmiş domatesi de üzerine ilave edin ve 5 dakika kadar pişirin.\n\n"
        "\t Yarım ay şeklinde doğradığınız 1 adet kuru soğanı ve elma dilim kesilmiş 3 adet patatesi fırın kabının tabanına yayın. Köfteleri de üzerlerine yerleştirin.\n\n"
        "\t Son olarak 2 adet küp doğranmış kırmızı biber küpleri ve hazırladığınız domates sosunu da köftelerin üzerine yayın.\n\n"
        "\t Ardından önceden ısıtılmış 180 derece fırında, 35- 40 dakika,  üzerleri hafif kızarana kadar pişirin ve sıcak olarak servis edin. Afiyet olsun.\n\n",
    "\t Malzemeler:\n\n"
        "\t Keki İçin:\n\n"
        "\t 3 adet yumurta\n\n"
        "\t 1/2 su bardağı toz şeker\n\n"
        "\t 1/2 su bardağı sıvı yağ\n\n"
        "\t 1 su bardağı hindistan cevizi\n\n"
        "\t 1 su bardağı galeta unu\n\n"
        "\t 1 su bardağı ceviz içi (ince çekilmiş)\n\n"
        "\t 1 paket kabartma tozu\n\n"
        "\t Kreması için:\n\n"
        "\t 1 litre süt\n\n"
        "\t 1 su bardağı mısır nişastası\n\n"
        "\t 1 çay bardağı toz şeker\n\n"
        "\t 1 paket vanilin\n\n"
        "\t 1 paket toz krem şanti\n\n"
        "\t Şerbeti için:\n\n"
        "\t 1,5 su bardağı su\n\n"
        "\t 1 su bardağı toz şeker\n\n"
        "\t 2 damla taze sıkılmış limon suyu\n\n"
        "\t Üzeri İçin:\n\n"
        "\t 1 su bardağı hindistan cevizi\n\n"
        "\t Tarif:\n\n"
        "\t Tatlının şerbeti için; su ve toz şekeri derin bir karıştırma kabına alın. Şeker taneleri eriyene kadar sürekli karıştırdığınız şerbet karışımını kısık ateşte 15 dakika kadar kaynatın.\n\n"
        "\t Kıvam alıp şurup kıvamına yaklaşan şerbete limon suyunu ekleyip kestirdikten sonra ocaktan alın. Soğuması için ayrı bir yerde dinlendirin.\n\n"
        "\t Tatlının kekini hazırlamak için; oda sıcaklığında beklettiğiniz yumurtaları derin bir karıştırma kabına kırın. Toz şeker ilavesiyle şeker taneleri tamamen eriyene kadar karıştırın.\n\n"
        "\t Sırasıyla; sıvı yağ, rendelenmiş Hindistan cevizi, galeta unu, ince çekilmiş ceviz içi ve kabartma tozu ekleyip karıştırma işlemini sürdürün.\n\n"
        "\t Pişireceğiniz kalıbı sıvı yağ ile yağlayın. Hazırladığınız kek karışımını eşit olarak yaydıktan sonra önceden ısıtılmış 160 derece fırında 30 dakika kadar pişirin.\n\n"
        "\t Üzerine önceden hazırladığınız soğuk şerbeti döküp içine çekmesi için bekletin.\n\n"
        "\t Kreması için; süt, nişasta ve toz şekeri derin bir tencereye alıp sürekli karıştırarak orta ateşte pişirin. Muhallebi kıvamına gelen kremayı ocaktan indirmeden önce vanilin ekleyin ve karıştırıp ocaktan alın.\n\n"
        "\t Ocaktan aldıktan sonra toz krem şanti ilavesiyle çırparak karıştırın.\n\n"
        "\t Krema karışımını şerbetini çeken tatlının üzerine yayın.\n\n"
        "\t Hindistan cevizini de tüm yüzeye serpiştirin.\n\n"
        "\t Buzdolabında soğuttuktan sonra süsleyip sevdiklerinizle afiyetle tüketin.\n\n",
    "\t Malzemeler:\n\n"
        "\t Kreması İçin:\n\n"
        "\t 1 yemek kaşığı nişasta\n\n"
        "\t 3 adet yumurta\n\n"
        "\t 1 adetlimon kabuğu rendesi(ve suyu)\n\n"
        "\t 1 su bardağı şeker\n\n"
        "\t 1 kutu sıvı krema\n\n"
        "\t 600 gram labne peyniri\n\n"
        "\t 1 paket vanilya\n\n"
        "\t Tabanı İçin:\n\n"
        "\t 2 paket tam buğdaylı bisküvi\n\n"
        "\t 125 gram eritilmiş tereyağı\n\n"
        "\t Sosu İçin:\n\n"
        "\t 1/2 su bardağı şeker\n\n"
        "\t 2 yemek kaşığı mısır nişastası\n\n"
        "\t 1 su bardağı su\n\n"
        "\t 1 paket vanilya\n\n"
        "\t 300 gram frambuaz(donmuş ya da taze)\n\n"
        "\t Tarif:\n\n"
        "\t Kelepçeli kalıbın kenar duvarlarını kaplamak için yağlı kağıtları kesin. Tabanı ve kenarları margarin sürerek yağlı kağıt ile kaplayın.\n\n"
        "\t Daha sonra kalıbın alt tabanını su geçmemesini sağlamak için alüminyum folyo ile kaplayın.\n\n"
        "\t Frambuzları yarım su bardağı şeker ve bir bardak su ile karıştırıp buzdolabında beklemeye alın.\n\n"
        "\t Pasta tabanı için 2 paket tam buğday unlu bisküviyi rondodan geçirin.\n\n"
        "\t 125 gram eritilmiş tereyağı üzerine ekleyip rondodan, bisküvilerle birlikte geçirin.\n\n"
        "\t Hazırlamış olduğunuz kalıba bisküvili karışımı bir spatula ya da bardak ile iyice bastırarak yayın.\n\n"
        "\t Pürüzsüz bir yüzey yaratmaya çalışın. Dinlenmesi için pasta tabanını kalıbıyla birlikte buzdolabında bekletin.\n\n"
        "\t Cheesecake kreması için; 3 yumurta, 600 gram labne peynir, 1 su bardağı toz şeker, 1 kutu sıvı krema, 1 limon kabuğu rendesi ve suyu, 1 paket vanilya, 1 yemek kaşığı dolusu nişastayı bir kaba alın.\n\n"
        "\t Mikserle pürüzsüz hale gelinceye kadar karıştırın.\n\n"
        "\t Buzdolabından çıkardığınız kalıba kremalı karışımı dökün.\n\n"
        "\t Su ile doldurduğunuz derin bir fırın tepsisinin içine kalıbı yerleştirerek 25 dakika 180 derecede; 25-30 dakika da 150 derecede pişirin.\n\n"
        "\t Daha sonra fırını kapatıp bir saat de fırın içinde bekletin. Bu şekilde cheesecake çatlamadan pişecektir.\n\n"
        "\t Cheesecake dışarıda soğurken farmbuazlı sosu hazırlamaya başlayın. Dolaptan çıkardığınız frambuazları bir blender ile ezin.\n\n"
        "\t Bir çay bardağı su ile 2 yemek kaşığı nişastayı bir kasede açın.\n\n"
        "\t Tencereye ekleyin. Kısık ateşte karıştırarak pişirin.\n\n"
        "\t Sosunuz yoğun bir kıvama gelince içine bir paket vanilya ekleyip, karıştırın ve soğumaya bırakın.\n\n"
        "\t Cheesecake ve frambuaz sosu soğuyunca, cheesecake’in üzerine sosunu döküp buzdolabında 1 gece beklemeye alın.\n\n"
        "\t Buzdolabından çıkardığınız cheesecake’i kalıbından çıkarıp taze ya da donmuş frambuazla ve nane yapraklarıyla süsleyerek servis edebilirsiniz. Afiyet olsun.\n\n\n",
  ];
}
